version: "3.7"
services:
  db:
    image: postgres:alpine
    env_file: .env

  app:
    build: ./src
    ports:
      - 8000:8000
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - db
    env_file: .env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
    env_file: .env